### ISSUE TITLE
[Encoder] Save to File

### ISSUE THREAD

**Issue by LauraWebdev** [CKegel/Web-SSTV#4]
Hey there, awesome project! It would be cool if one could save the encoded audio to a file, I'm currently using an app to encode my images and using the web version would make my workflow so much easier.

**Comment by commandcontrolQ** [comment]
I've just created a pull request from my fork to add this functionality. It'll hopefully be merged in a few days.

**Comment by CKegel** [comment]
Please let me know if you encounter any issues with the download feature I just made live. I am working to refactor it to be a little cleaner but for now this should do. -73
