### ISSUE TITLE
decoder not working

### ISSUE THREAD

**Issue by 81XxserhatxX18** [CKegel/Web-SSTV#7]
decoder is not working

**Comment by wiz30** [comment]
+1, doesn't listen to anything, won't even show up a mic perms

**Comment by Kidou-Software** [comment]
i have "Waiting for Audio Feed..." on opera LVL6 (core: 114.0.5282.148
![image](https://github.com/user-attachments/assets/7f67c4a9-4641-4a36-b31d-78901021b496)
)

**Comment by CKegel** [comment]
What is currently live is not fully implemented. I did not intend to deploy that page yet, as indicated by the text noting that it is not operational at the bottom of the page.
